export const voters = [
  { sno: 1, epicNo: "MGY4694196", nameHi: "मो असलम", parentNameHi: "मो नेयाजउद्दीन", gender: "Male", sectionNo: "16/1" },
  { sno: 2, epicNo: "MGY4694204", nameHi: "साजदा खातून", parentNameHi: "पति: मो असलम", gender: "Female", sectionNo: "16/1" },
  { sno: 3, epicNo: "MGY4694352", nameHi: "मो हमजा", parentNameHi: "पिता: मो खलील", gender: "Male", sectionNo: "16/1" },
  { sno: 4, epicNo: "MGY4694360", nameHi: "रेहाना खातून", parentNameHi: "पति: मो हमजा", gender: "Female", sectionNo: "16/1" },
  { sno: 5, epicNo: "MGY4694220", nameHi: "मो मुदस्सर नज़र", parentNameHi: "पिता: मो असलम", gender: "Male", sectionNo: "16/1" },
  { sno: 6, epicNo: "MGY4694345", nameHi: "नेहा नाज़", parentNameHi: "पिता: मो असलम", gender: "Female", sectionNo: "16/1" },
  { sno: 7, epicNo: "MGY4694212", nameHi: "मो सादिक अनवर", parentNameHi: "पिता: मो असलम", gender: "Male", sectionNo: "16/1" },
  { sno: 8, epicNo: "MGY6168215", nameHi: "विकास होरो", parentNameHi: "पिता: मारिया होरो", gender: "Male", sectionNo: "16/1" },
  { sno: 9, epicNo: "MGY4507356", nameHi: "शैलेश कुमार राम", parentNameHi: "पिता: गोविन्द राम", gender: "Male", sectionNo: "16/1" },
  { sno: 10, epicNo: "MGY5065164", nameHi: "मासोमात बतुलून", parentNameHi: "पति: हफीज़", gender: "Female", sectionNo: "16/1" },

  { sno: 11, epicNo: "MGY5414313", nameHi: "विक्की राम", parentNameHi: "पिता: शंकर राम", gender: "Male", sectionNo: "16/1" },
  { sno: 12, epicNo: "MGY5044177", nameHi: "मोहम्मद एहसान", parentNameHi: "पिता: मोहम्मद जिलानी", gender: "Male", sectionNo: "16/1" },
  { sno: 13, epicNo: "MGY5065065", nameHi: "रहमतुल्लाह", parentNameHi: "पिता: मोहम्मद जिलानी", gender: "Male", sectionNo: "16/1" },
  { sno: 14, epicNo: "MGY5044292", nameHi: "सबीना परवीन", parentNameHi: "पति: मोहम्मद एहसान", gender: "Female", sectionNo: "16/1" },
  { sno: 15, epicNo: "MGY5417548", nameHi: "अमानुल्लाह", parentNameHi: "पिता: मोहम्मद जिलानी", gender: "Male", sectionNo: "16/1" },
  { sno: 16, epicNo: "MGY5990114", nameHi: "मोहम्मद अकरम", parentNameHi: "पिता: मोहम्मद अमानुल्लाह", gender: "Male", sectionNo: "16/1" },
  { sno: 17, epicNo: "MGY5040324", nameHi: "मोहम्मद असलम", parentNameHi: "पिता: मोहम्मद गयासुद्दीन", gender: "Male", sectionNo: "16/1" },
  { sno: 18, epicNo: "MGY5040241", nameHi: "मुनीजा खातून", parentNameHi: "पति: मोहम्मद असलम", gender: "Female", sectionNo: "16/1" },
  { sno: 19, epicNo: "MGY4507539", nameHi: "नबिला एनाम", parentNameHi: "पिता: मो. इनामुल हक", gender: "Female", sectionNo: "16/1" },
  { sno: 20, epicNo: "MGY4507554", nameHi: "मो. इनामुल हक", parentNameHi: "पिता: नाजिर अली", gender: "Male", sectionNo: "16/1" },

  { sno: 21, epicNo: "MGY4507547", nameHi: "नाहिद एनाम", parentNameHi: "पति: मो. इनामुल हक", gender: "Female", sectionNo: "16/1" },
  { sno: 22, epicNo: "MGY4035317", nameHi: "राज कमल टोप्पो", parentNameHi: "पिता: रोबर्ट टोप्पो", gender: "Male", sectionNo: "16/1" },
  { sno: 23, epicNo: "MGY5791397", nameHi: "जॉनसन प्रतीक टोप्पो", parentNameHi: "पिता: जेकब टोप्पो", gender: "Male", sectionNo: "16/1" },
  { sno: 24, epicNo: "MGY5725130", nameHi: "सुचिता खलखो", parentNameHi: "पति: रवि रंजन शालशो", gender: "Female", sectionNo: "16/1" },
  { sno: 25, epicNo: "MGY4034872", nameHi: "रोज सुशीला लिलता टोप्पो", parentNameHi: "पति: एल. के. टोप्पो", gender: "Female", sectionNo: "16/1" },
  { sno: 26, epicNo: "MGY4034997", nameHi: "ग्रेगोरी मिंज", parentNameHi: "पिता: मार्टिन मिंज", gender: "Male", sectionNo: "16/1" },
  { sno: 27, epicNo: "MGY4035002", nameHi: "सुभागिनी मिंज", parentNameHi: "पति: ग्रेगोरी मिंज", gender: "Female", sectionNo: "16/1" },
  { sno: 28, epicNo: "MGY4034880", nameHi: "सावन कुमुद टोप्पो", parentNameHi: "पिता: लहरोई कुमार", gender: "Male", sectionNo: "16/1" },
  { sno: 29, epicNo: "MGY5769245", nameHi: "पूजा कुमारी", parentNameHi: "पिता: स्व. राम स्वरूप राम", gender: "Female", sectionNo: "16/1" },
  { sno: 30, epicNo: "MGY6131692", nameHi: "खुशी कुमारी", parentNameHi: "पिता: कृष्णा राम", gender: "Female", sectionNo: "16/1" },

  { sno: 31, epicNo: "MGY5076203", nameHi: "खैरुन निशा", parentNameHi: "पति: शब्बीर अली", gender: "Female", sectionNo: "16/1" },
  { sno: 32, epicNo: "MGY5076328", nameHi: "मोहम्मद मुस्तार", parentNameHi: "पिता: मोहम्मद अजीजलु", gender: "Male", sectionNo: "16/1" },
  { sno: 33, epicNo: "MGY6326730", nameHi: "सीमा देवी", parentNameHi: "पति: रिक्की राम", gender: "Female", sectionNo: "16/1" },
  { sno: 34, epicNo: "MGY6256028", nameHi: "अब्दुल सत्तार", parentNameHi: "पिता: अब्दुल जब्बार", gender: "Male", sectionNo: "16/1" },
  { sno: 35, epicNo: "MGY5326749", nameHi: "एजाज अहमद", parentNameHi: "पिता: मोहम्मद मोबिनुद्दीन", gender: "Male", sectionNo: "16/1" },
  { sno: 36, epicNo: "MGY5896295", nameHi: "मोहम्मद आरिफ", parentNameHi: "पिता: मोहम्मद नईम", gender: "Male", sectionNo: "16/1" },
  { sno: 37, epicNo: "MGY4906111", nameHi: "मोहम्मद ईशा खान", parentNameHi: "पिता: स्व. फैजल हक", gender: "Male", sectionNo: "16/1" },
  { sno: 38, epicNo: "MGY5336870", nameHi: "गुलाम हसन", parentNameHi: "पिता: शमशाद हसन", gender: "Male", sectionNo: "16/1" },
  { sno: 39, epicNo: "MGY4906210", nameHi: "मोहम्मद असरफ", parentNameHi: "पिता: स्व. मोहम्मद मुस्तफा", gender: "Male", sectionNo: "16/1" },
  { sno: 40, epicNo: "MGY4906145", nameHi: "अकबरी खातून", parentNameHi: "पति: मोहम्मद ईशा", gender: "Female", sectionNo: "16/1" },

  { sno: 41, epicNo: "MGY4907606", nameHi: "मो. रिजवान", parentNameHi: "पिता: मो. जाकिर हुसैन", gender: "Male", sectionNo: "16/1" },
  { sno: 42, epicNo: "MGY4907812", nameHi: "बब्लू", parentNameHi: "पिता: मो. सकुर", gender: "Male", sectionNo: "16/1" },
  { sno: 43, epicNo: "MGY4906103", nameHi: "जमीला खातून", parentNameHi: "पति: स्व. मोहम्मद अख्तर", gender: "Female", sectionNo: "16/1" },
  { sno: 44, epicNo: "MGY4907614", nameHi: "नसीमा परवीन", parentNameHi: "पति: मो. रिजवान", gender: "Female", sectionNo: "16/1" },
  { sno: 45, epicNo: "MGY4907580", nameHi: "आबदा खातून", parentNameHi: "पति: मुश्तफा", gender: "Female", sectionNo: "16/1" },
  { sno: 46, epicNo: "MGY4907481", nameHi: "रेखा देवी", parentNameHi: "पति: राज कुमार राम", gender: "Female", sectionNo: "16/1" },
  { sno: 47, epicNo: "MGY4906657", nameHi: "मो नसीम", parentNameHi: "पिता: मो. खादीम", gender: "Male", sectionNo: "16/1" },
  { sno: 48, epicNo: "MGY4906954", nameHi: "मो. नौसाद", parentNameHi: "पिता: सलीम", gender: "Male", sectionNo: "16/1" },
  { sno: 49, epicNo: "MGY4906921", nameHi: "मो. आफताब आलम", parentNameHi: "पिता: मोहम्मद गुलाब", gender: "Male", sectionNo: "16/1" },
  { sno: 50, epicNo: "MGY4906699", nameHi: "असिमना खातून", parentNameHi: "पति: मो नासिम", gender: "Female", sectionNo: "16/1" },

  { sno: 51, epicNo: "MGY4906905", nameHi: "नजमा खातून", parentNameHi: "पति: अब्दुल सत्तार", gender: "Female", sectionNo: "16/1" },
  { sno: 52, epicNo: "MGY4906756", nameHi: "रोकसाना खातून", parentNameHi: "पति: मो. नौशाद", gender: "Female", sectionNo: "16/1" },
  { sno: 53, epicNo: "MGY4907598", nameHi: "मो. इमरान", parentNameHi: "पिता: मोख्तार अहमद", gender: "Male", sectionNo: "16/1" },
  { sno: 54, epicNo: "MGY4907853", nameHi: "मो. असफाक", parentNameHi: "पिता: मो. अनवर", gender: "Male", sectionNo: "16/1" },
  { sno: 55, epicNo: "MGY4983185", nameHi: "जोहरा खातून", parentNameHi: "पति: नेहाल सबीह", gender: "Female", sectionNo: "16/1" },
  { sno: 56, epicNo: "MGY5245592", nameHi: "मोहम्मद रमजान", parentNameHi: "पिता: मोहम्मद आशिक", gender: "Male", sectionNo: "16/1" },
  { sno: 57, epicNo: "MGY4907531", nameHi: "रजिया बेगम", parentNameHi: "पति: मो. आफताब आलम", gender: "Female", sectionNo: "16/1" },
  { sno: 58, epicNo: "MGY4907259", nameHi: "बिलकिस फातमा", parentNameHi: "पति: मो. नौशाद", gender: "Female", sectionNo: "16/1" },
  { sno: 59, epicNo: "MGY5336912", nameHi: "मोहम्मद एजाज अहमद", parentNameHi: "पिता: मोहम्मद इकबाल", gender: "Male", sectionNo: "16/1" },
  { sno: 60, epicNo: "MGY4907473", nameHi: "सीमा देवी", parentNameHi: "पति: टिंकू राम", gender: "Female", sectionNo: "16/1" },

  { sno: 61, epicNo: "MGY4906087", nameHi: "फहमीदा खातून", parentNameHi: "पति: मो. रिजवान", gender: "Female", sectionNo: "16/1" },
  { sno: 62, epicNo: "MGY4907275", nameHi: "सोफिया परवीन", parentNameHi: "पति: मो. नसीम", gender: "Female", sectionNo: "16/1" },
  { sno: 63, epicNo: "MGY4907622", nameHi: "अहमद अली", parentNameHi: "पिता: सैयद अबुबकर", gender: "Male", sectionNo: "16/1" },
  { sno: 64, epicNo: "MGY5336896", nameHi: "मोहम्मद इफ्तियाज", parentNameHi: "पिता: आसिया सुलताना", gender: "Male", sectionNo: "16/1" },
  { sno: 65, epicNo: "MGY4907341", nameHi: "मीनू परवीन", parentNameHi: "पति: मो. शमीम", gender: "Female", sectionNo: "16/1" },
  { sno: 66, epicNo: "MGY4907333", nameHi: "मो. तसलीम", parentNameHi: "पिता: मो. मुस्लिम", gender: "Male", sectionNo: "16/1" },
  { sno: 67, epicNo: "MGY5085097", nameHi: "महेलाका अजमेरी", parentNameHi: "पिता: अब्दुल कय्यूम", gender: "Female", sectionNo: "16/1" },
  { sno: 68, epicNo: "MGY4906129", nameHi: "शफीना परवीन", parentNameHi: "पिता: मो. ईशा खान", gender: "Female", sectionNo: "16/1" },
  { sno: 69, epicNo: "MGY4907358", nameHi: "मो. शमीम", parentNameHi: "पिता: मो. मुस्लिम", gender: "Male", sectionNo: "16/1" },
  { sno: 70, epicNo: "MGY4906947", nameHi: "तब्बसुम परवीन", parentNameHi: "पति: मो. तसलीम", gender: "Female", sectionNo: "16/1" },

  { sno: 71, epicNo: "MGY5082011", nameHi: "गौतम कुमार राम", parentNameHi: "पिता: महावीर राम", gender: "Male", sectionNo: "16/1" },
  { sno: 72, epicNo: "MGY4906095", nameHi: "मो फिरदोश अख्तर", parentNameHi: "पिता: स्व. मो. अख्तर", gender: "Male", sectionNo: "16/1" },
  { sno: 73, epicNo: "MGY4907408", nameHi: "सुल्ताना परवीन", parentNameHi: "पिता: शकीला खातून", gender: "Female", sectionNo: "16/1" },
  { sno: 74, epicNo: "MGY4906376", nameHi: "रूही परवीन", parentNameHi: "पिता: मोहम्मद असरफ", gender: "Female", sectionNo: "16/1" },
  { sno: 75, epicNo: "MGY4906061", nameHi: "साजिद अख्तर", parentNameHi: "पिता: स्व. अख्तर", gender: "Male", sectionNo: "16/1" },
  { sno: 76, epicNo: "MGY4906079", nameHi: "मोहम्मद शाहनवाज आलम", parentNameHi: "पिता: मो. इरशाद", gender: "Male", sectionNo: "16/1" },
  { sno: 77, epicNo: "MGY4907390", nameHi: "महजबीं परवीन", parentNameHi: "पिता: मो. मुस्लिम", gender: "Female", sectionNo: "16/1" },
  { sno: 78, epicNo: "MGY4907515", nameHi: "मो. वसीम", parentNameHi: "पिता: यूसुफ परवेज", gender: "Male", sectionNo: "16/1" },
  { sno: 79, epicNo: "MGY4907325", nameHi: "मो. मोसीम", parentNameHi: "पिता: मो. यूसुफ", gender: "Male", sectionNo: "16/1" },
  { sno: 80, epicNo: "MGY4906939", nameHi: "पिंकी देवी", parentNameHi: "पति: गुड्डू राम", gender: "Female", sectionNo: "16/1" },

  { sno: 81, epicNo: "MGY4908000", nameHi: "मो. शोएब खान", parentNameHi: "पिता: मो. मुस्लिम", gender: "Male", sectionNo: "16/1" },
  { sno: 82, epicNo: "MGY5745880", nameHi: "निखत परवीन", parentNameHi: "पिता: एस. खालिद अहमद", gender: "Female", sectionNo: "16/1" },
  { sno: 83, epicNo: "MGY4907416", nameHi: "शमीमा परवीन", parentNameHi: "पति: मोहम्मद सैफुल्लाह", gender: "Female", sectionNo: "16/1" },
  { sno: 84, epicNo: "MGY4907499", nameHi: "नील कमल रवि", parentNameHi: "पिता: दुर्गा राम", gender: "Male", sectionNo: "16/1" },
  { sno: 85, epicNo: "MGY4906392", nameHi: "यास्मीन परवीन", parentNameHi: "पति: मो. समीम", gender: "Female", sectionNo: "16/1" },
  { sno: 86, epicNo: "MGY4906244", nameHi: "अशिया परवीन", parentNameHi: "पिता: असलम", gender: "Female", sectionNo: "16/1" },
  { sno: 87, epicNo: "MGY5051396", nameHi: "सदफ सईद", parentNameHi: "पिता: मो. सईद", gender: "Female", sectionNo: "16/1" },
  { sno: 88, epicNo: "MGY4907465", nameHi: "प्रवीण कुमार राम", parentNameHi: "पिता: राज कुमार राम", gender: "Male", sectionNo: "16/1" },
  { sno: 89, epicNo: "MGY4906301", nameHi: "मो एजाजुल", parentNameHi: "पिता: मो. लावर", gender: "Male", sectionNo: "16/1" },
  { sno: 90, epicNo: "MGY6110431", nameHi: "अजमुन परवीन", parentNameHi: "पिता: मोहम्मद वाहिद", gender: "Female", sectionNo: "16/1" },

  { sno: 91, epicNo: "MGY5245600", nameHi: "मोहम्मद यूसुफ", parentNameHi: "पिता: मोहम्मद आशिफ", gender: "Male", sectionNo: "16/1" },
  { sno: 92, epicNo: "MGY5365853", nameHi: "बेली खातून", parentNameHi: "पिता: सायरा खातून", gender: "Female", sectionNo: "16/1" },
  { sno: 93, epicNo: "MGY4906350", nameHi: "मोहम्मद सैफ", parentNameHi: "पिता: मोहम्मद असरफ", gender: "Male", sectionNo: "16/1" },
  { sno: 94, epicNo: "MGY4907788", nameHi: "मो. कुबान", parentNameHi: "पिता: खातून निशा", gender: "Male", sectionNo: "16/1" },
  { sno: 95, epicNo: "MGY4907457", nameHi: "दीपा देवी", parentNameHi: "पति: दीपकुमार राम", gender: "Female", sectionNo: "16/1" },
  { sno: 96, epicNo: "MGY4907523", nameHi: "नेहा परवीन", parentNameHi: "पिता: मो. अख्तर", gender: "Female", sectionNo: "16/1" },
  { sno: 97, epicNo: "MGY5051404", nameHi: "शफाक सईद", parentNameHi: "पिता: मो. सईद", gender: "Female", sectionNo: "16/1" },
  { sno: 98, epicNo: "MGY4906137", nameHi: "रुखसार परवीन", parentNameHi: "पिता: मोहम्मद ईशा खान", gender: "Female", sectionNo: "16/1" },
  { sno: 99, epicNo: "MGY5051412", nameHi: "फलक सईद", parentNameHi: "पिता: मो. सईद", gender: "Female", sectionNo: "16/1" },
  { sno: 100, epicNo: "MGY4906871", nameHi: "सागर राम", parentNameHi: "पिता: पवन राम", gender: "Male", sectionNo: "16/1" },
];
